name: Fetch

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/main.rs'
      - '.github/workflows/fetch.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/main.rs'
      - '.github/workflows/fetch.yml'
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust 1.85.1
      uses: actions-rs/toolchain@v1
      with:
        toolchain: '1.85.1'

    - name: Cache cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose

    - name: Run application
      run: cargo run > ref-prices.json

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: "GManTheMarioGuy"
        author_email: "gman36147@gmail.com"
        add: "ref-prices.json --force"
        message: "ref prices fetching"
        github_token: ${{ secrets.GITHUB_TOKEN }}
