name: Fetch

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  updateStats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.85.1'

      - run: |
          cargo run --release > ref-prices.json

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: "REF Prices Updater"
          author_email: "gman36147@gmail.com"
          add: "ref-prices.json --force"
          message: "ref prices fetching"
